### ISSUE TITLE
JAGGS error

### ISSUE THREAD

**Issue by MichaelRFox** [ndphillips/yarrr#1]
Whenever I run the sample scripts I get the following error:

Error: .onLoad failed in loadNamespace() for 'rjags', details:
  call: fun(libname, pkgname)
  error: Failed to locate any version of JAGS version 4

The rjags package is just an interface to the JAGS library
Make sure you have installed JAGS-4.x.y.exe (for any x >=0, y>=0) from
http://www.sourceforge.net/projects/mcmc-jags/files

**Comment by darny** [comment]
Hi. 

I experienced the same error. **Nathaniel Phillips** @ndphillips  resolved it. He replied: 

> The issue you're having is with creating the HDI bars. The function that creates the HDIs uses the BEST package, which I've found for some machines does not always work properly.
Try manually installing the BEST package first with the following code:
install.packages('BEST')

Hope this helps. 

I'm a big fan of the Pirate Plot. A lot of info can be communicated in 1 graph.

**Comment by ndphillips** [comment]
I recently changed the HDI functions from the BEST package to the BayesFactor package. I find functions in the BayesFactor package to be much more stable than those from the BEST package. It should work much better now!
