### ISSUE TITLE
Error when using 3 IV

### ISSUE THREAD

**Issue by nuskcalb** [ndphillips/yarrr#10]
When using 3 IV:
> formula = DV ~ IV1 + IV2 + IV3

I get the following error:
> #Error in if (max(dens.y.i) > width.max) { : missing value where TRUE/FALSE needed

I attach a reproducible example.

Thanks!

[Bug 3.zip](https://github.com/ndphillips/yarrr/files/413017/Bug.3.zip)

**Comment by ndphillips** [comment]
Unfortunately only 1 or 2 IVs are supported at this time :( I hope to add a third IV in the future...
