### ISSUE TITLE
Some repo suggestions

### ISSUE THREAD

**Issue by pat-s** [ndphillips/yarrr#18]
First of all: Loving your package after taking the first look! Keep it up! I also had the idea of doing a project in this direction! May be I can contribute to your package. 

Some suggestions regarding your Github repo (now that your package is available on CRAN) for possible further contributions :
- Add a `NEWS.md` file tracking your version changes
- Add Travis CI build checking
- Syntax highlighting of you README (suggesting to build with an .Rmd file)
- Tag your released versions on Github under "releases"
- Setup a "dev" branch to let the "master" branch become more stable
- Tag the github version (master branch) with a .9000 at the end, indicating that this is the "dev" version
- Set up a list with pending feature updates in "issues" or "projects" so others can contribue more easily

Recommended reading: Hadleys book "R packages": http://r-pkgs.had.co.nz/

**Comment by ndphillips** [comment]
Hi @pat-s Thanks very much for the tips! Much appreciated!

**Comment by ndphillips** [comment]
Thanks for the great updates @pat-s! As I said in another thread, I'm new to package development and Git, so I think I merged this with the Master branch prematurely instead of the dev branch. But I think it's working ok :)

And yes I've read excerpts from Hadley's book but clearly need to read it in more detail now, thanks for the reminder!

**Comment by pat-s** [comment]
You´re welcome! I also just at the beginning of package development so there is much left to learn! 

# Branches & Pull requests
Merging pull requests with the master branch is right. I specifically address my pull requests to your master branch (coming from my 'dev' branch)! 

What is important for you: Make your changes in your own 'dev' branch and then send a pull request to your own 'master' branch. By this, you can reference open issues/requests to this pull request. Also, others can see bundled commits addressing a specific problem in this pull requests. This is more convenient for others than just looking at single commits. This all makes it easier to work together on Github 👍 

# Travis CI
I already added all settings for a TRAVIS CI build in #23 . What you need to do is to create an account on https://travis-ci.org and enable the checking for your 'yarrr' repo. 

# Versioning
I saw that you removed the `install_github()` in your README. To be able to install the 'dev' version of your package (which always references to your 'master' branch), you should 

1. Re-add `install_github("ndphillips/yarrr", build_vignettes = TRUE)` to your README (using the README.Rmd file)
2. Change the version in Description to something different than the actual version on CRAN (0.09). It is suggested to use '.9000' at the end to indicate that this is the dev version from Github. Subsequently this would be '0.0.9.9000'. So if one installs from GitHub, one will immediately see in his package directory that the GitHub version is installed rather than the CRAN one. 

**Note**: I really like your package and your fast responses. Keep it up and do not hesitate to ask :)
