### ISSUE TITLE
Error in seq.default(plot.min, plot.max, by = best.step.size)

### ISSUE THREAD

**Issue by jmacarter** [ndphillips/yarrr#2]
I'm receiving the following error with my pirateplot() call:
> pirateplot(formula = (Allowed_CMS_per_Infusion) ~ Drug + POS,
+            data = InfusedDrugsAnnual,
+            theme.o = 1,
+            gl.col = gray(.8),
+            point.pch = 16,
+            main = "RA Infusion\nCost of Drug, by Place of Service, 2014 Data",
+            ylab = "Cost per Infusion (based on CMS ASP)",
+            xlab = "Drug, by Place of Service",
+ )

Error in seq.default(plot.min, plot.max, by = best.step.size) : 
  'from' must be of length 1

There is a fairly large range in Allowed_CMS_per_Infusion:
> max(InfusedDrugsAnnual$Allowed_CMS_per_Infusion)
[1] 12120.37
> min(InfusedDrugsAnnual$Allowed_CMS_per_Infusion)
[1] 741.586

But I do need all data points. It seems a best.step.size = 1000 should be sufficient. Any suggestions?

Thanks in advance.

**Comment by ndphillips** [comment]
Hmmm, that's strange. Can you send me your data so I can diagnose the issue?

**Comment by jmacarter** [comment]
code and dataset sent to your yarr.book email address. Thanks

**Comment by jmacarter** [comment]
Bug fixed and verified in latest release - thanks!
