### ISSUE TITLE
Boxplots as option for param `inf`

### ISSUE THREAD

**Issue by pat-s** [ndphillips/yarrr#20]
I am combining bean plots and box plots for quite some time. However, the "inference" part of `pirateplot` does only allow for Bayesian calculations and does not provide the option for simple box plots. 

Would be great to have a third `inf` option "box plots" which displays (at least) median + 25% & 75% quantiles. 0% & 100% quantiles could be made optional with some additional short line (compared to median + 25% & 75%). 

I´ll check out if I get this working. 

Thoughts?

**Comment by ndphillips** [comment]
@pat-s Yes a few people have made the same request. I like the idea of an interquartile-range as an argument to `inf`, however I am reluctant to include a full boxplot as that would make the plot very cluttered....

**Comment by pat-s** [comment]
@ndphillips If you make it optional there is no problem I guess. It just expands the user options and everybody has to decide what to in-or exclude into the plot. IQR would be the first step, vertical lines for 0% and 100% the next. Let's see what comes around!

**Comment by ndphillips** [comment]
`iqr` is now an option for the `inf` argument to set inference band limits to the inter-quartile range!

**Comment by ndphillips** [comment]
So I thought about the boxplot option a bit more...and I really think that combining a pirateplot with a boxplot just doesn't make sense to me.

For example, I think the following looks pretty awful

```
pirateplot(len ~ supp + dose, data = ToothGrowth)

boxplot(len ~ supp + dose, 
        data = ToothGrowth, 
        at = c(1, 2, 4, 5, 7, 8), add = T, yaxt = "n", xaxt = "n")
```

![image](https://cloud.githubusercontent.com/assets/8480980/19364517/caa24f40-918e-11e6-9c7b-657b20a310bb.png)

Can you convince me this is a good option by showing me a combination of a pirateplot (or beanplot) and boxplot that actually looks good?

**Comment by pat-s** [comment]
@ndphillips I did not mean to overlay the basic `boxplot` function but to just use the same look you are already using for the current `inf` options for a start. I really like that style, I am just missing my quantiles ;)

Then, as the next step, optionally adding horizontal lines at 0% and 100%. I would not add the vertical lines between 75% to 100% and 0% to 25% for the moment because these might collide with the data points. 

I will see what I can do, sit tight :)

**Comment by ndphillips** [comment]
Thanks for the updates! As I'm new to package development (and git) I'm pretty sure I fucked up the merge - as I merged everything into the master branch instead of the dev branch. Other than that I think it went well :)

I made a few slight changes to your merge

- `quant.add` is now just `quant`, and the arguments are in fractions rather than percentages. This makes more sense to me.

- `quant` is applied independently of the `inf` argument. So even if you have `inf = 'hdi'`, you can still add quantile lines with `quant`

**Comment by ndphillips** [comment]
I think we've got this one covered, thanks again! If new ideas come up, just reopen.
