### ISSUE TITLE
Add global color option

### ISSUE THREAD

**Issue by pat-s** [ndphillips/yarrr#22]
After some testing, it seems that one currently has to change all colors of params 

`point.col, bar.col, bean.border.col, inf.col, average.line.col, bar.border.col` 

if one wants to set colors manually. 

An option which wraps all these color settings in one argument would be great!

**Comment by ndphillips** [comment]
@pat-s If you set the `pal` argument to a single color, then the color will be passed to all elements.

e.g.;

`pirateplot(weight ~ Time, data = ChickWeight, pal = "black"`

**Comment by pat-s** [comment]
@ndphillips Ahh thanks! Just saw your example in which you set all "black". However one can also just pass a vector with colors.
