### ISSUE TITLE
Wrong size of box in a pirateplot

### ISSUE THREAD

**Issue by BERENZ** [ndphillips/yarrr#3]
I run the example codes for `pirateplot` function and the result is not as we would expect. Please see the codes its results below.

```
pirateplot(formula = weight ~ Diet,
           data = ChickWeight,
           main = "Theme 1",
           theme.o = 1
)
```
![plot1](https://cloud.githubusercontent.com/assets/3464669/14942481/589a5ef8-0fbe-11e6-91cb-bce13335ad7b.png)

```
pirateplot(formula = weight ~ Diet,
           data = ChickWeight,
           main = "Theme 1 + grayscale",
           theme.o = 1,
           pal = "black"
)

```

![plot2](https://cloud.githubusercontent.com/assets/3464669/14942483/5ea5bdf6-0fbe-11e6-9e83-b624a0f66fd0.png)

```
> sessionInfo()
R version 3.2.4 (2016-03-16)
Platform: x86_64-apple-darwin14.5.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] en_US.UTF-8/UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] yarrr_0.1
```

**Comment by ndphillips** [comment]
The output looks perfect to me. What do you think is wrong?

On 01 May 2016, at 17:02, Maciej Beręsewicz <notifications@github.com<mailto:notifications@github.com>> wrote:


I run the example codes for pirateplot function and the result is not as we would expect. Please see the codes its results below.

pirateplot(formula = weight ~ Diet,
           data = ChickWeight,
           main = "Theme 1",
           theme.o = 1
)


[plot1]<https://cloud.githubusercontent.com/assets/3464669/14942481/589a5ef8-0fbe-11e6-91cb-bce13335ad7b.png>

pirateplot(formula = weight ~ Diet,
           data = ChickWeight,
           main = "Theme 1 + grayscale",
           theme.o = 1,
           pal = "black"
)



[plot2]<https://cloud.githubusercontent.com/assets/3464669/14942483/5ea5bdf6-0fbe-11e6-9e83-b624a0f66fd0.png>

> sessionInfo()
R version 3.2.4 (2016-03-16)
Platform: x86_64-apple-darwin14.5.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] en_US.UTF-8/UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] yarrr_0.1

**Comment by BERENZ** [comment]
I am not sure why these boxes (bars?) represent. Should it be the same as for boxplot? That is bottom of the box is Q1 and top is Q3?

**Comment by ndphillips** [comment]
The bars represent the central tendency of each distribution. By default it is the mean, but you can change the function with the line.fun argument.

The points represent the raw data

The symmetrical beans represent the density.




On 02 May 2016, at 09:27, Maciej Beręsewicz <notifications@github.com<mailto:notifications@github.com>> wrote:


I am not sure why these boxes (bars?) represent. Should it be the same as for boxplot? That is bottom of the box is Q1 and top is Q3?

**Comment by ndphillips** [comment]
@BERENZ  If you check out the latest version of the package, you'll see a detailed vignette which explains each element of the pirateplot(). Here's a scrreenshot of the description: [Pirateplot element description](https://dl.dropboxusercontent.com/u/7618380/pirateplotss.png)

To get the latest version and see the vignette, run the following

`devtools::install_github('ndphillips/yarrr', build_vignettes = T)`
` vignette("pirateplot", package = "yarrr")`
