### ISSUE TITLE
Distribution lines extend beyond axes

### ISSUE THREAD

**Issue by oscci** [ndphillips/yarrr#35]
I am loving pirate plots, and am planning to include these in a paper I am writing.
However, I have one problem which is that the distribution lines for some of then extend beyond the range of the y-axis. I attach an example.
![screen shot 2016-12-19 at 17 52 49](https://cloud.githubusercontent.com/assets/7351645/21308439/f702ac46-c614-11e6-9416-6b38a11a0a83.png)

Thanks. (NB I am v inexperienced with github - not sure if I would get an email if you can respond to this - if not, could you please just drop me one at dorothy.bishop@psy.ox.ac.uk)

**Comment by ndphillips** [comment]
Hi @oscci . This pesky problem keeps coming up. Can you check and see if the problem still occurs in the latest version of the package on GitHub?

```
install.packages("devtools") # Only if you don't have it
devtools::install_github("ndphillips/yarrr", build_vignettes = TRUE)
```

**Comment by oscci** [comment]
Done that, but I now get an error saying
Error in pirateplot(formula = MLUw ~ ageband, data = summary_dat, xlab = "Age Band",  : 
  unused arguments (hdi.o = 0.7, line.o = 1, bar.o = 0.1)
Here is the original bit of script:
tiff(file = "Figure 1.tiff", width = 3200, height = 3200, units = "px", res = 500)
par(xpd=T)
pirateplot(formula = MLUw ~ ageband,
           data = summary_dat,
           xlab = "Age Band",
           ylab = "MLUw",
           main = "",
           pal = "black",
           hdi.o = .7,
           line.o = 1,
          bar.o = .1,
           bean.o = .1,
           point.o = .1,
           point.pch = 16,
           back.col = gray(.97))
dev.off()

**Comment by ndphillips** [comment]
yes some of the arguments have been changed in this version. 
change `hdi.o` to `inf.f.o`, `line.o` to `avg.line.o` , and `bar.o` to `bar.f.o`

**Comment by oscci** [comment]
Ach sorry. Made changes but it's still not fixed.
![screen shot 2016-12-20 at 07 48 56](https://cloud.githubusercontent.com/assets/7351645/21333185/ebc71c08-c688-11e6-8de6-a40704485cb1.png)

**Comment by ndphillips** [comment]
I think the problem is that you have `par(xpd = TRUE)`. This will allow plotting elements to extend outside of the plotting region. Do you need this on?

**Comment by oscci** [comment]
No! Many thanks. That has fixed it .
