### ISSUE TITLE
package ‘yarr’ is not available (for R version 3.3.3)

### ISSUE THREAD

**Issue by jobreu** [ndphillips/yarrr#38]
It seems that yarr is not (yet) working with the most recent version of R (3.3.3)

**Comment by ndphillips** [comment]
Did you spell yarrr with 3 rs?

`install.packages("yarrr")`

**Comment by jobreu** [comment]
Classic copy paste error =D Thx for the quick response & sorry for bothering you with my inability to (double-)check package names!

**Comment by ndphillips** [comment]
No worries, I make the same mistake sometimes
