### ISSUE TITLE
Calling piratepal() suppresses x-axis labels in future calls to pirateplot()

### ISSUE THREAD

**Issue by rnlanders** [ndphillips/yarrr#39]
Calling piratepal() causes the x-axis labels in any subsequent call to pirateplot() to disappear, at least in the RStudio IDE.  I cannot figure out how to get the x-axis labels to reappear - even if xlab is set - without restarting the R console.  I suspect it is related to piratepal() itself not having any x-labels.  

More specifically, this call has x axis labels before piratepal() is called but not after:
`pirateplot(data = dataset,
           formula = y ~ x1 + x2,
           xlab = "X1",
           ylab = "Y",
           main = "Time 1 Measures",
           pal = "southpark")`

**Comment by ndphillips** [comment]
Hmmmm, I am unable to replicate the problem. What happens if you run the following:

```
library(yarrr)

pirateplot(weight ~ Time, data = ChickWeight)
piratepal("southpark")
pirateplot(weight ~ Time, data = ChickWeight)

```

**Comment by rnlanders** [comment]
No, but I can replicate it with this:


library(yarrr)



pirateplot(weight ~ Time, data = ChickWeight)

piratepal()

pirateplot(weight ~ Time, data = ChickWeight)


---
Richard N. Landers, Ph.D.
Associate Professor, Industrial/Organizational Psychology
Associate Editor, Computers in Human Behavior
Associate Editor, Simulation & Gaming
Old Dominion University | Mills Godwin Building 346E, Norfolk VA 23529
Website: http://rlanders.net | Blog: http://neoacademic.com
Tw: @rnlanders | Ph: 757-683-4212 | Fx: 757-683-5087

**Comment by ndphillips** [comment]
Ah, the problem is that running `piratepal()` changed the plot margins. I thought I reset them in the code but apparently it wasn't working.

In your code, you can fix it by resetting the plotting margins back to the default using

`par(mar = c(5, 4, 4, 1) + .1`

...and then creating the second plot again.

I also just fixed the code to perform this automatically in yarrr v0.1.5. Please try installing this version from github and let me know if it works:
```
install.packages("devtools") # Only if you don't have it
devtools::install_github("ndphillips/yarrr")
library("yarrr")
pirateplot(weight ~ Time, data = ChickWeight)
piratepal()
pirateplot(weight ~ Time, data = ChickWeight)
```

**Comment by rnlanders** [comment]
That fixed it, thanks!  I’m also encountering a problem getting xlab to work on a two IV plot, but I’m not confident that’s not my own fault yet.  :)

---
Richard N. Landers, Ph.D.
Associate Professor, Industrial/Organizational Psychology
Associate Editor, Computers in Human Behavior
Associate Editor, Simulation & Gaming
Old Dominion University | Mills Godwin Building 346E, Norfolk VA 23529
Website: http://rlanders.net | Blog: http://neoacademic.com
Tw: @rnlanders | Ph: 757-683-4212 | Fx: 757-683-5087
