### ISSUE TITLE
Can't rotate the orientation of the x axis' notations

### ISSUE THREAD

**Issue by Eugllena** [ndphillips/yarrr#4]
I want to rotate the orientation of the x axis' notations (e.g. from fig. 1 to fig. 2), but when I change the value of parameter las of par(), it has no effect. 

![vertical](https://cloud.githubusercontent.com/assets/17746996/15810727/2d14ab94-2bd4-11e6-8bc8-3861832743ca.png)
![horizontal](https://cloud.githubusercontent.com/assets/17746996/15810736/3f944c98-2bd4-11e6-9691-99aa40693100.png)

I found that parameters of par() such as las and adj can't pass to function pirateplot().

A suggestion, could you add an option to the function pirateplot() which allows the users to order the x variables according to the their corresponding y values?

**Comment by ndphillips** [comment]
Thanks for the suggestion

With regards to the par argument, I don’t think it would work as it would need to be passed to both the axis() functions and the plot() functions. Maybe there’s a way to get that to work but I don’t know how!

If you want to customise the axes, I recommend turning them off (xaxt = “n”, yaxt = “n”) in the pirateplot(), then adding them yourself after with axis()

regard to ordering the x variables according to the y values: This is a good idea. I’ll try to implement this in the next version (which should be out in a week)

**Comment by Eugllena** [comment]
Thank you! I look forward to the next version.

**Comment by ndphillips** [comment]
The option to order groups by their means is now available with the `sortx` argument (e.g.; `sortx = mean`)

I don't think I'll include the `par` updates as there are already too many arguments to pirateplot, I think I'll leave it to the user to add such custom label orientations after the plot with `mtext`
