### ISSUE TITLE
Problems after drawing a 3 IV plot

### ISSUE THREAD

**Issue by gorkang** [ndphillips/yarrr#42]
After drawing a plot with 3 IV, there are some unintended consequences. See the example below:

`library(yarrr)`

`# Draw a plot with 3 IVs`
`pirateplot(formula = weight ~ Time * Chick * Diet, data = ChickWeight)`

`# This plot fills only in the top-left part of the plot area, as in `par(mfrow = c(2,2))` instead of filling the whole plot area`
`pirateplot(formula = weight ~ Time * Chick, data = ChickWeight)`

An easy way to solve it is to add `par(mfrow = c(1,1))` after each pirateplot with 3 IVs, but it would be nice if the pirateplot() function would do that for us :)

**Comment by ndphillips** [comment]
I'm not quite sure what you're looking for... here's what I get with your code which seems to be exactly what should happen. Can you tell me a bit more about what you'd like the code to return?

![image](https://user-images.githubusercontent.com/8480980/31486670-811b29aa-af38-11e7-9dfb-1ab76fd6f591.png)

**Comment by gorkang** [comment]
Sorry if it wasn't clear enough.

Yes, that is the first plot, the one with 3 IV. The problem arises in the next plot you draw.

**Step 1** - all good here:
```
# Draw a plot with 3 IVs
pirateplot(formula = weight ~ Time * Chick * Diet, data = ChickWeight)

```

**Step 2**. You draw a plot with 1 or 2 IV, and the plot does not fill the whole plot area in RStudio
```
# This plot fills only in the top-left part of the plot area, as inpar(mfrow = c(2,2))instead of filling the whole plot area
pirateplot(formula = weight ~ Time * Chick, data = ChickWeight)

```
This is the output:
![pirate1](https://user-images.githubusercontent.com/6491790/31494615-7e443ff4-af2a-11e7-8615-5a9cb360d902.png)

But it should be:
![pirate2](https://user-images.githubusercontent.com/6491790/31494635-9d49a8f8-af2a-11e7-9309-18c05c0ea57f.png)
