### ISSUE TITLE
Producing default plots everytime

### ISSUE THREAD

**Issue by billybrady** [ndphillips/yarrr#45]
Hi!

For some reason, no matter what data I input or variables I specify, I'm getting this "default" plot drawn. 

![image](https://user-images.githubusercontent.com/20144715/40212872-603da1ac-5a20-11e8-8628-6af3b3ff32d0.png)

I've tried reloading R, having only the yarr package loaded, and multiple data sets, all to no avail. Are there any common issues that could be causing this? I'm running R 3.4.3 with the following code, for example:

install_github("ndphillips/yarrr")
library(yarrr)

test <- read_csv('test.csv')

pirateplot(formula = DV ~ IV,
           data = test,
           main = "T2 Accuracy by Word Type",
           theme = 1,
           gl.col = gray(.7))

"test" is a file with one column (IV) demarcating categories A-D (sorted) and another column (DV) with a range of accuracy scores.

**Comment by ndphillips** [comment]
Thanks for catching this! This was indeed a silly bug -- in my latest update I was playing around with some hard coded test data but forgot to remove it from the code in the final push!

It should be fixed now. Please try installing again and see if it's indeed working

**Comment by billybrady** [comment]
Working great now - thanks!

**Comment by ndphillips** [comment]
Yeah that was a pretty embarrassing bug, thanks for letting me know! Hopefully no one else is stuck with it!
