### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by MartinsRodrigo** [ndphillips/yarrr#5]
When I run the following code:

```
install.packages("devtools")
library(devtools)
install_github("ndphillips/yarrr")
```

I get an odd error:

```
Downloading GitHub repo ndphillips/yarrr@master
from URL https://api.github.com/repos/ndphillips/yarrr/zipball/master
Installing yarrr
"D:/Program Files/R/R-3.3.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/Rodrigo/AppData/Local/Temp/Rtmp6lvboK/devtools1e1043f87b45/ndphillips-yarrr-6800fe1"  \
  --library="D:/Program Files/R/R-3.3.1/library" --install-tests 

Error: Command failed (127)
```

Can't find any help googling it. Do you have any idea? Here's my system informations:

```
R.Version()
$platform
[1] "x86_64-w64-mingw32"

$arch
[1] "x86_64"

$os
[1] "mingw32"

$system
[1] "x86_64, mingw32"

$status
[1] ""

$major
[1] "3"

$minor
[1] "3.1"

$year
[1] "2016"

$month
[1] "06"

$day
[1] "21"

$`svn rev`
[1] "70800"

$language
[1] "R"

$version.string
[1] "R version 3.3.1 (2016-06-21)"

$nickname
[1] "Bug in Your Hair"
```

**Comment by ndphillips** [comment]
Hmmm, that's a new one. I was making several updates to the package
yesterday and some of them had bugs. Can you try reinstalling it now and
see what happens?

Nathaniel

**Comment by MartinsRodrigo** [comment]
Same error. I'll try to install some older version and see what happens.

**Comment by ndphillips** [comment]
@MartinsRodrigo  Can you also try using the `build_vignettes = T` option and see if that helps?

`devtools::install_github('ndphillips/yarrr', build_vignettes = T)`

**Comment by MartinsRodrigo** [comment]
Just tried in another machine, but i got another error:

```
install_github("ndphillips/yarrr",  build_vignettes = T)
Downloading GitHub repo ndphillips/yarrr@master
from URL https://api.github.com/repos/ndphillips/yarrr/zipball/master
Installing yarrr
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/marcela/AppData/Local/Temp/RtmpwxcXhw/devtools1cd8117a6939/ndphillips-yarrr-2e36d63" --library="C:/Users/marcela/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'yarrr' ...
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'DBI'
Error : package 'dplyr' could not be loaded
ERROR: lazy loading failed for package 'yarrr'
* removing 'C:/Users/marcela/Documents/R/win-library/3.3/yarrr'
Error: Command failed (1)
```

So I installed DBI, dplyr, coda and BayesFactor packages before trying again and it worked. 

Don't know what's going on, but now i have YARR  =)

**Comment by ndphillips** [comment]
Ok I'm glad it's working now! I'm still not sure what the problems were before...

**Comment by andrewxstewart** [comment]
I had this too. Worked after installing DBI, dplyr, coda, BayesFactor, jpeg,knitr,rmarkdown packages, then using:
install_github("ndphillips/yarrr",  build_vignettes = T)

**Comment by kernpanik** [comment]
To make things more complicated in Debian, RStudio crashed every time I tried to install BayesFactor with
`install.packages("BayesFactor", dependencies = TRUE)` 

For me, the only working solution was to download the source code, open a Terminal window, navigate to the folder containing the tar.gz and installing it with:
`R CMD INSTALL BayesFactor_0.9.12-4.2.tar.gz`

Finally: Good ol' Pirateplots on my GNU/Linux machine.
