### ISSUE TITLE
additional argument 'sub' not working

### ISSUE THREAD

**Issue by zhihaozheng** [ndphillips/yarrr#6]
'sub' is an argument that should be passed on to the plot function. Looks like it is not working.

Codes to reproduce:

You can see the subtitle at bottom under xlab.
`plot(sin, -pi, 2*pi, main = 'test', sub = 'sub')`

No subtitle.
`pirateplot(formula = weight ~ Diet, data = ChickWeight, main = "Theme 1", sub = "sub", theme.o = 1, pal = "appletv")`

Thanks.

**Comment by ndphillips** [comment]
Fixed!
