### ISSUE TITLE
Error when data are constant

### ISSUE THREAD

**Issue by nuskcalb** [ndphillips/yarrr#8]
When trying to plot an interaction where a few conditions have no variance (100% accuracy), Pirate plot stops plotting when reaches one of the no variance bins with the following error:

> "Error in t.test.default(dv.i, conf.level = inf.p) : data are essentially constant"

Please see the attached files for a reproducible example.

[Pirate plot Bug.zip](https://github.com/ndphillips/yarrr/files/406977/Pirate.plot.Bug.zip)

**Comment by ndphillips** [comment]
Thanks for catching this. I believe the bug has been fixed in 0.0.3!

**Comment by nuskcalb** [comment]
Thanks! That error is gone but I can see some new problems:

**1. No individual responses are shown when Accuracy <100% (when there is variance)**
2. Probably unrelated: should CI go over 100%?

Please see attached image with the new plot.
![v0 0 3](https://cloud.githubusercontent.com/assets/6491790/17559355/e11dc250-5f15-11e6-9f47-487c0653df64.png)

**Comment by ndphillips** [comment]
1. I actually decided to specifically remove the points and densities when the data are binary (as yours are). In this case, the densities and points don't really help much (in my opinion).

2. Good point with the CIs. This was the result of calculating frequentist 95% CIs (https://en.wikipedia.org/wiki/Binomial_distribution). I'll just fixed this so they are cut off at 0 and 1. However, I fear this makes the interval difficult to interpret relative to the 95% level of confidence. A better solution is to stick with Bayesian 95% HDIs with inf = "hdi". These are calculated directly from the beta distribution (see https://en.wikipedia.org/wiki/Checking_whether_a_coin_is_fair) and are much easier to interpret.

**Comment by nuskcalb** [comment]
1. Getting rid of the points et al. hides some important information (as sample size), doesn't it? Although I understand they are a lot less informative in binary variables, I still kind of miss them... maybe a parameter to be able to hide them at will? :)

2. Thanks!

**Comment by ndphillips** [comment]
Yeah good point, I added the points back by default (though I imagine there must be a better way to visualise the sample size...). Here's the result:

`ChickWeight$weight.bin <- ChickWeight$weight > 200`
`yarrr::pirateplot(weight.bin ~ Time, data = ChickWeight, point.o = .02)`

![image](https://cloud.githubusercontent.com/assets/8480980/17583474/7df76df6-5fb1-11e6-9b5c-5b5840a1b352.png)

**Comment by nuskcalb** [comment]
Works great now. Thanks a lot!

**Comment by ndphillips** [comment]
:)
