### ISSUE TITLE
2 issues: variable labels and yaxis range

### ISSUE THREAD

**Issue by nuskcalb** [ndphillips/yarrr#9]
Two small issues:

1. The variable labels are shown OK in te R Studio preview, but when viewed full screen or the plot is saved (.png), only part of the name appears. For example, "Problema" -> "ema" (see the attached .png)
 
2. The automatic y axis limit seems to be set in a slightly weird way. In this example, my data range is 0.49 to -0.71 and the axis are 0.2 / -0.8 (of course, ylim can be used to manually set the desired range, but maybe there is anything weird going on).

I attach a reproducible example, plus the plot saved as png from Rstudio.

[Bug 2.zip](https://github.com/ndphillips/yarrr/files/407078/Bug.2.zip)

**Comment by ndphillips** [comment]
Thanks for catching these! I believe I fixed them in the new version (0.0.3). Please reinstall and see if the error persists.
